class Organization():
  def get(self):
    return {
      "cdc": "Centers for Disease Control and Prevention", "od": "Office of the Director",
      "om": "Office of Mission Support", "ocoo": "Office of the Chief Operating Officer",
      "oadc": "Office of the Associate Directory of Communications",
      "ocio": "Office of the Chief Information Officer",
      "oed": "Office of Equal Employment Opportunity and Workplace Equity",
      "oga": "Office of Global Affairs", "ohs": "Office of Health Equity",
      "opa": "Office of Policy, Performance, and Evaluation",
      "ostlts": "Office of State, Tribal, Local and Territorial Support",
      "owcd": "Office of Women’s Health and Health Equity",
      "cSELS": "Center for Surveillance, Epidemiology, and Laboratory Services",
      "csels": "Center for Surveillance, Epidemiology, and Laboratory Services",
      "ddphss": "Deputy Director for Public Health Science and Surveillance",
      "cgH": "Center for Global Health", "cgh": "Center for Global Health",
      "cid": "Center for Preparedness and Response", "cpr": "Center for Preparedness and Response",
      "ncezid": "National Center for Emerging and Zoonotic Infectious Diseases",
      "ncird": "National Center for Immunization and Respiratory Diseases",
      "nchhstp": "National Center for HIV, Viral Hepatitis, STD, and TB Prevention",
      "nccdphp": "National Center for Chronic Disease Prevention and Health Promotion",
      "nceh": "National Center for Environmental Health",
      "atsdr": "Agency for Toxic Substances and Disease Registry",
      "ncipc": "National Center for Injury Prevention and Control",
      "ncbddd": "National Center on Birth Defects and Developmental Disabilities",
      "nchs": "National Center for Health Statistics",
      "niosh": "National Institute for Occupational Safety and Health",
      "ddid": "Deputy Director for Infectious Diseases",
      "ddnidd": "Deputy Director for Non-Infectious Diseases",
      "cfa": "Center for Forecasting and Outbreak Analytics",
      "ophdst": "Office of Public Health Data, Surveillance, and Technology",
      "amd": "Office of Advanced Molecular Detection", "oamd": "Office of Advanced Molecular Detection",
    }

