class Organization():
  def get(self, sorted_keys=False):
    orgs = {
      "amd": "Office of Advanced Molecular Detection (AMD)",
      "atsdr": "Agency for Toxic Substances and Disease Registry (ATSDR)",
      "cSELS": "Center for Surveillance, Epidemiology, and Laboratory Services (CSELS)",
      "cdc": "Centers for Disease Control and Prevention (CDC)",
      "cfa": "Center for Forecasting and Outbreak Analytics (CFA)",
      "cgH": "Center for Global Health (CGH)",
      "cgh": "Center for Global Health (CGH)",
      "cid": "Center for Preparedness and Response (CID)",
      "cpr": "Center for Preparedness and Response (CPR)",
      "csels": "Center for Surveillance, Epidemiology, and Laboratory Services (CSELS)",
      "ddid": "Deputy Director for Infectious Diseases (DDID)",
      "ddnidd": "Deputy Director for Non-Infectious Diseases (DDNIDD)",
      "ddphss": "Deputy Director for Public Health Science and Surveillance (DDPHSS)",
      "ncbddd": "National Center on Birth Defects and Developmental Disabilities (NCBDDD)",
      "nccdphp": "National Center for Chronic Disease Prevention and Health Promotion (NCCDPHP)",
      "nceh": "National Center for Environmental Health (NCEH)",
      "ncezid": "National Center for Emerging and Zoonotic Infectious Diseases (NCEZID)",
      "nchhstp": "National Center for HIV, Viral Hepatitis, STD, and TB Prevention (NCHHSTP)",
      "nchs": "National Center for Health Statistics (NCHS)",
      "ncipc": "National Center for Injury Prevention and Control (NCIPC)",
      "ncird": "National Center for Immunization and Respiratory Diseases (NCIRD)",
      "niosh": "National Institute for Occupational Safety and Health (NIOSH)",
      "oadc": "Office of the Associate Directory of Communications (OADC)",
      "oamd": "Office of Advanced Molecular Detection (OAMD)",
      "ocio": "Office of the Chief Information Officer (OCIO)",
      "ocoo": "Office of the Chief Operating Officer (OCOO)",
      "oed": "Office of Equal Employment Opportunity and Workplace Equity (OED)",
      "oga": "Office of Global Affairs (OGA)",
      "ohs": "Office of Health Equity (OHS)",
      "opa": "Office of Policy, Performance, and Evaluation (OPA)",
      "ophdst": "Office of Public Health Data, Surveillance, and Technology (OPHDST)",
      "ostlts": "Office of State, Tribal, Local and Territorial Support (OSTLTS)",
      "owcd": "Office of Women's Health and Health Equity (OWHD)"
    }
    return orgs
